pipeline:
  staging-publish:
    image: plugins/docker
    repo: nossas/bonde-payments
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  staging-deploy-payments:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    group: deploying
    service: cronjobs/payments
    docker_image: nossas/bonde-payments:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  staging-deploy-payments-transferred:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    group: deploying
    service: cronjobs/payments-transferred
    docker_image: nossas/bonde-payments:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  staging-deploy-payments-waiting-funds:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    group: deploying
    service: cronjobs/payments-waiting-funds
    docker_image: nossas/bonde-payments:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  production-publish:
    image: plugins/docker
    repo: nossas/bonde-payments
    tags:
      - ${DRONE_TAG##v}
    when:
      status: success
      event: tag

  production-deploy-payments:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    group: deploying_prod
    service: cronjobs/payments
    docker_image: "nossas/bonde-payments:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: tag

  production-deploy-payments-transferred:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    group: deploying_prod
    service: cronjobs/payments-transferred
    docker_image: "nossas/bonde-payments:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: tag

  production-deploy-payments-waiting-funds:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    group: deploying_prod
    service: cronjobs/payments-waiting-funds
    docker_image: "nossas/bonde-payments:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: tag

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: bonde_bots
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]

services:
  database:
    image: postgres:9.6
    queue:
      i
