pipeline:
  publish-docker-staging:
    image: plugins/docker
    repo: nossas/bonde-payments
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  deploy-staging-payments:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: staging/payments
    docker_image: "nossas/bonde-payments:${DRONE_BRANCH}"
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  publish-docker-production:
    image: plugins/docker
    repo: nossas/bonde-payments
    tags:
      - ${DRONE_TAG##v}
    when:
      status: success
      event: tag

  deploy-production-payments:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    group: deploying_prod
    service: bonde/payments
    docker_image: "nossas/bonde-payments:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: tag

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: bonde_bots
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]

services:
  database:
    image: postgres:9.6
    queue:
      i
