default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  url: postgres://postgres:3x4mpl3@db.devel:5432/bonde

test: &test
  <<: *default
  url: postgres://postgres:3x4mpl3@db.devel:5432/hub_test

staging:
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
